// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD62iiO-fL44uHhI3g-7agtEEKOcdEyTEI',
    appId: '1:95240316218:web:d28fac6abc0a65142d5c03',
    messagingSenderId: '95240316218',
    projectId: 'nextar-test-proj',
    authDomain: 'nextar-test-proj.firebaseapp.com',
    storageBucket: 'nextar-test-proj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlLRbeantIIAW78NpoMthLWLxuob2r6VQ',
    appId: '1:95240316218:android:be4bec31acde00be2d5c03',
    messagingSenderId: '95240316218',
    projectId: 'nextar-test-proj',
    storageBucket: 'nextar-test-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6UXnq5FJM6DLkyclv0MuQAMJKg1axJys',
    appId: '1:95240316218:ios:8a93a1de5f96003c2d5c03',
    messagingSenderId: '95240316218',
    projectId: 'nextar-test-proj',
    storageBucket: 'nextar-test-proj.firebasestorage.app',
    iosBundleId: 'com.example.nextarProducts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6UXnq5FJM6DLkyclv0MuQAMJKg1axJys',
    appId: '1:95240316218:ios:8a93a1de5f96003c2d5c03',
    messagingSenderId: '95240316218',
    projectId: 'nextar-test-proj',
    storageBucket: 'nextar-test-proj.firebasestorage.app',
    iosBundleId: 'com.example.nextarProducts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD62iiO-fL44uHhI3g-7agtEEKOcdEyTEI',
    appId: '1:95240316218:web:2614238486a06cad2d5c03',
    messagingSenderId: '95240316218',
    projectId: 'nextar-test-proj',
    authDomain: 'nextar-test-proj.firebaseapp.com',
    storageBucket: 'nextar-test-proj.firebasestorage.app',
  );

}